import type { Metadata } from "next";
import localFont from "next/font/local";
import { Noto_Sans_KR } from 'next/font/google';
import "./globals.css";
import { RqProvider } from "@/components/rq-provider";
import { AuthSubscriber } from "@/components/auth-subscriber";
import { Toaster } from "@/components/ui/toaster";
import { ThemeProvider } from "@/components/theme-provider";



const notoSansKr = Noto_Sans_KR({
  subsets: ["latin"],
  weight: ["100", "400", "700", "900"],
  variable: '--font-note-sans-kr'
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (


    <html lang="en">
      <body
        className={`${notoSansKr.variable}  antialiased`}>
        <RqProvider>
          <AuthSubscriber>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem>
              {children}
            </ThemeProvider>
            <Toaster />
          </AuthSubscriber>
        </RqProvider>
      </body>
    </html>

  );
}
